// Generated by CoffeeScript 1.6.3
(function() {
  var addToCart, getSkuId, parseCartInfo;

  parseCartInfo = function() {
    var c, cartForm, cartInfo, _i, _len;
    cartInfo = {};
    cartForm = $('.add-to-cart-form').serializeArray();
    for (_i = 0, _len = cartForm.length; _i < _len; _i++) {
      c = cartForm[_i];
      cartInfo[c.name] = c.value;
    }
    return cartInfo;
  };

  getSkuId = function() {
    var availableSize, rt, skuId;
    availableSize = [];
    $('select[name="skuAndSize"] option').each(function() {
      if ($(this).hasClass('exp-pdp-size-not-in-stock')) {
        return;
      }
      return availableSize.push($(this).val());
    });
    if (availableSize.length === 0) {
      return null;
    }
    skuId = availableSize[0].split(':')[0];
    rt = {
      sizes: availableSize,
      skuId: skuId
    };
    return rt;
  };

  addToCart = function(qty) {
    var cartInfo, request, sku;
    if (qty === void 0) {
      qty = 1;
    }
    cartInfo = parseCartInfo();
    cartInfo.qty = qty;
    sku = getSkuId();
    if (sku === null) {
      return;
    }
    cartInfo.skuAndSize = sku.sizes[0];
    cartInfo.skuId = sku.skuId;
    request = {
      url: 'https://secure-store.nike.com/us/services/jcartService',
      dataType: 'jsonp',
      data: cartInfo
    };
    return $.ajax(request);
  };

  window.addToCart = addToCart;

  $(document).ready(function() {
    return addToCart();
  });

}).call(this);
